### ISSUE TITLE
Readme.md git clone path not correct now

### ISSUE THREAD

**Issue by LondonWillGeorge** [toddbirchard/flasklogin-tutorial#20]
Hi, 

I noticed README.md still shows git clone path as: ...hackersandslackers.. when it should be ...toddbirchard...

Thank you so much for this tutorial.

After getting somewhat confused by trying to combine Digital Ocean flask login tutorial with digital ocean flask uswsgi nginx tutorial, I just cloned your whole shebang. Looks like I might have a working entry point, then can just follow the digital ocean uwsgi nginx tut to get this going as base for secure enough website. Dig Ocean tut also told me how to get free SSL by the way, I imagine anyone doing your tut might also be interested in both SSL and nginx setup, if there were links at end of tutorial:
https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uwsgi-and-nginx-on-ubuntu-20-04

Dig Ocean flask login tut puts create_app() inside another method, with an import statement inside this method for the create_app() which looks quite naughty (I'm wondering if this is bad idea in any programming language even), and caused me too much pain trying to get this working with entry point.

Otherwise I'm quite intrigued to know if your prestigious colleague renovate-bot is a human or not. https://github.com/renovate-bot doesnt load for me here anyway...

**Comment by toddbirchard** [comment]
Haha, `renovate-bot` is a plugin for keeping dependencies up to date.

Thanks for point this out; I'll have this fixed in the readme. While this repo _should_ be under the **hackersandslackers** org, it accumulated too much attention (and stars/favorites) for me to right my wrongs :(
